### ISSUE TITLE
Server: completePurchase inconsistency with other drivers

### ISSUE THREAD

**Issue by coatesap** [thephpleague/omnipay-sagepay#32] opened 2015-04-28 10:24 UTC
Currently, in order to genuinely complete the purchase of a SagePay Server transaction, the calling code needs to call not only `$gateway->completePurchase()` but also `$response->confirm()`. This is slightly annoying, as it means the behaviour and usage is different to other drivers, and the beauty of OmniPay is having drop in replacement drivers, as far as possible.

As far as I can see, there wouldn't be any major downsides to `ServerGateway` handling the confirm process, thereby negating the need for extra calling code. Does anyone have any thoughts on this (I'd be happy to provide a PR for the changes)?

**Comment by coatesap** [comment] 2015-04-28 10:47
My suggestion - so that it doesn't break any existing usage - is that if a `returnUrl` parameter is passed to `$gateway->completePurhase()`, it calls `$response->confirm()` automatically.

Eg:

    $params = [
        'transactionId' => $ourId,
        'transactionReference' => $gatewayId,
        'returnUrl' => $customerReturnUrl
    ];
    $response = $gateway->completePurchase($params)->send();
    // because 'returnUrl' was set, completePurchase called confirm itself

**Comment by judgej** [comment] 2015-04-28 10:49
Hi @coatesap, do you have any examples showing how you would like the callback process to work?

As it stands now, `$response->confirm()` is an end-point - it responds to SagePay and exits. That should only be done if the callback handler is happy with the result it gets from `$gateway->completePurchase()`, and has had an opportunity to log the details it gets from that into storage and possibly queued up for handling by the merchant application. I'm not sure how those two steps can be merged, given that the merchant site callback handler needs to process the result and make a decision on what is returned to SagePay (confirm, invalid, or error)

**Comment by judgej** [comment] 2015-04-28 11:01
You may also want to call `$response->invalid()` with a return URL. This would be the case if the security token (the signature) does not validate, or the amount being expected does not match the amount being authorised. This can arguably be done within `$gateway->completePurchase()` , so long as there is a way to log this in the application; the application needs to know what was sent back to SagePay, so it knows whether the transaction notification was valid or not.

Perhaps if the confirm/invalid/error methods did not exit the script, leaving that up to the application after it has done all its logging, that would work. And if those methods keep a flag when a result has been "sent" (i.e. echoded) so calling those methods a second time does not output a second time, would help in migration.

**Comment by judgej** [comment] 2015-04-28 11:08
So the problem is possibly that `$response->confirm()` and friends exit the script to make sure no further output is generated. `$gateway->completePurchase()` should probably generate the result (i.e. return the three lines of text to SagePay), BUT we don't want that exiting the script because the result needs to be logged by the application.

I think that could work, by removing confirm/invalid/error (or changing them to they do nothing more than just exit, for backwards compatibility) and generate (i.e. echo) the real return code in `$gateway->completePurchase()`. What do you think?

**Comment by judgej** [comment] 2015-04-28 11:55
I think this would also help with Issue #16 in which an invalid signature results in an exception being raised and some clumsy code being needed to handle it. Instead of raising an exception, it could just echo the "error" return text and return an error status (not an exception) for logging. I think you may be on to a winner here :-)

**Comment by coatesap** [comment] 2015-04-28 16:49
@judgej - thanks for those thoughts and suggestions. I have realised now that whichever way this is done, it's not ideal. If we remove the exits, then this comes with it's own non-standardness in that the calling code needs to know whether to output something or redirect the customer's browser (if it's a callback from a gateway where the customer redirect is one and the same thing)...

I'll give this a little more thought!

**Comment by judgej** [comment] 2015-04-28 17:17
In this particular case, there is never a redirect. The notification callback must always return something: OK (confirm), INVALID or ERROR, plus an optional message. These are just echoed out as a couple of lines of text. The only thing that the callback should then do is to exit, after it has done its logging etc. but no other headers, redirects or content should be sent/returned.

How this compares to other gateway callbacks, I'm not sure. So far as I know, all the callbacks just return text and exit. Some may modify the HTTP response code though. They will all have their own formats: SagePay needs three (or two) lines of text, Authorise.Net SIM needs a HTML page with an embedded redirect returned, Helcim wants multiple lines of name:value pairs. They are all different, just to mess with our heads, but the underlying action is: return text, exit, done.

**Comment by judgej** [comment] 2015-05-01 09:11
just came across the discussion here that is loosely relevant:

https://github.com/thephpleague/omnipay/pull/215

It argues that `complete*()` should not be used in the callbacks at all, which is something I've always felt too, just because it feels unintuitive to me. Both this issue and that PR concern making the callback handling more consistent between the drivers, and more intuitive across the board.

**Comment by coatesap** [comment] 2015-05-02 06:51
Good find - I think that's exactly it. Gateway callbacks/notifications need a bit more thought at the generic omnipay level, so that regardless of their style of operation, they can be handled in a consistent fashion. 

With SagePay Server, because of the need to `exit` with a response to SagePay, we're always left with a need for it to be a two-stage operation. I'm not now so keen on my original proposal, as this would really just create the need for another method - something like `->exitIfRequired()` (which would again be non-standard unless it was implemented in the common layer).

Regarding the redirects following a callback - I should have been clearer - these take place in my own controller. This is completely generic callback handling code that currently serves a number of different gateways. It is how I've implemented it in our project, but I imagine anyone else interested in doing the same thing would probably implement it in a similar fashion.

Pseudo-code for speed:

    // callback received from gateway 
    // (might be behind-the-scenes paypal ipn style, 
    // or customer browser redirect, eg. barclays epdq)

    // try to identify the transaction to which this relates 
    // (either from the URL or the session)
    $params = ['stuff'];

    // let the driver do its thing
    $response = $gateway->completePurchase($params)->send();
    
    // update our database with the results, etc
    $this->handlePaymentResult($response, $params);

    // our current non-standard bit for SagePay
    if (method_exists($response, 'confirm')) {
        $response->confirm($customerReturnUrl);
    }

    // now, the majority of gateways won't care what happens now, 
    // so assuming this might be a customer browser redirect style callback, 
    // send them off to a suitable completion url
    $this->redirectToCompletionPage($customerReturnUrl)

I think actually, just standardising at the omnipay common level what that final method is called would probably be sufficient.

**Comment by judgej** [comment] 2015-05-02 07:43
I see - one handler for returns from the gateway, whether in-session or an out-of-session callback.

I tend to treat these as two separate things, since the callback does not share a session, so there are steps involved in pulling the transaction data from storage, which is is not (necessarily) needed when it is a simple gateway return. I can see the value in either approach.

**Comment by judgej** [comment] 2015-05-02 08:17
Just to expand this a little, when a callback is used (SagePay Server, Authorize.Net SIM et all) then the first thing the callback handler needs is the ID that it will use to identify the partially-complete transaction record that it has stored. None of the drivers help you do this at present - they leave you to look in the $POST or $REQUEST super-globals and to have the knowledge of what the ID is for each particular gateway.

So a helper method to get the ID, I believe would be useful. You still need to know which gateway driver to load, and maybe a parameter on the callback URL would indicate that (unless there is scope for some kind of auto-detect, based on what has been posted), but then getting the ID would be a consistent `$gateway->getStorageId()` or something like that.

SagePay will always send the vendor transaction ID with the callback, but Authorize.Net does not, and you need to create your own custom field to do that (or do as the current driver does and squeeze it into the invoiceId, which I don't like, but I suspect that choice has been inherited from the SDK - still wrong though IMO - an invoice and a payment are two different things). Anyway, there are perhaps some decisions to be made on which fields to use and which custom fields to be "owned" by OmniPay.

**Comment by coatesap** [comment] 2015-05-05 11:03
I think your approach of defining separate URLs for gateway callbacks and customer returns is a good idea, and allows the controller code to treat the request appropriately.

In that case... we probably could remove the `exit` from `confirm()` and allow `completePurchase()` to call `confirm()` itself. However, that would break all existing integrations!

**Comment by judgej** [comment] 2015-05-05 11:40
Yes, it would be a BC breaking change. But for OmniPay V3 it would be acceptable, with some documentation on how the behaviour differs and what kind of changes are needed for it to work. Maybe we need a "V3" label for these issues, or perhaps a V3 milestone? Each major version gives us a chance to refactor some of these design decisions, so we should make the most of it.

**Comment by kayladnls** [comment] 2015-05-05 14:19
BC Breaks can be allowed fro V3, and I would assume there will be a few of them. I'll be writing up an upgrade guide to go with the release of V3, though, so it shouldn't be an issue there.

**Comment by judgej** [comment] 2015-05-05 14:23
*Excited* :-)

**Comment by coatesap** [comment] 2015-07-20 10:48
After much discussion, I think essentially we're saying that SagePay Server's implementation is not quite right, and it should be using `notifyUrl` rather than `returnUrl`.

This would mean in this line: https://github.com/thephpleague/omnipay-sagepay/blob/e7d287e42ad0e4adddd1d1419af5b086f6a3897d/src/Message/ServerAuthorizeRequest.php#L25
in v3 we would change it to `$data['NotificationURL'] = $this->getNotifyUrl();` and make sure the notifyUrl value was always validated.

In `completeAuthorize` we would then call the current `confirm` code, and let the calling code handle the `exit;`. @judgej - does that sound like a fair summary?

**Comment by judgej** [comment] 2015-07-20 11:25
On the `notifyUrl` vs `returnUrl`, I added a change to [AuthorizeNet](https://github.com/thephpleague/omnipay-authorizenet/issues/16) to make the same change. It works for *either* at the moment, so is BC, and `returnUrl` can be removed for v3.00. That allows for some incremental changes. So yes to that.

The other one is a little more complicated. [Here is an example notify handler](https://github.com/academe/OmniPay-SagePay-Demo/blob/master/sagepay-confirm.php) for SagePay Server. Notice towards the end that once we know whether the authorisation was successful or not, we *still* need to be able to perform some action for the merchant site to register the result in the transaction storage. This happens between `send()` and `confirm()`, so we can't have `send()` exiting the script without the handler being able to do something with that result.

Now, just to throw this out there as an idea: would a callback be an appropriate way of handling this?

**Comment by coatesap** [comment] 2015-07-21 08:46
Regarding `notifyUrl` vs `returnUrl` - glad I'm not the only one who's spotted that in a few different drivers and thought it needed changing! 

Regarding how the notify handlers work - my initial thought was that if we said that all OmniPay notification handlers followed the same pattern of calling `completeWhatever()`, storing the result, then exiting, this would allow the `completeWhatever()` method to potentially write some kind of response to the buffer, which would then get output when the handler exited. I'm not sure if this is too prescriptive though.

**Comment by judgej** [comment] 2015-07-21 10:28
Yes, I can see how the HTTP message can be pushed out, then your notify handler can record the results/approve the invoice/push to a queue for processing etc. and then simply `exit` without outputting anything else.

For SagePay, you may want to choose the return URL depending on the result, but we can handle that with multiple (and optional) return URLs there - one for success, one for failure, and one for error. That would also get rid of [this dirty hack](https://github.com/academe/OmniPay-SagePay-Demo/blob/master/sagepay-confirm.php#L43) since we won't need to recreate the response object to fire out the error response - it could do that itself, then raise the exception, then the notify handler could log it and `exit`.

I like that idea.

**Comment by judgej** [comment] 2015-07-21 10:42
What do you think about the notify handler in Authorize.Net?

https://github.com/thephpleague/omnipay-authorizenet/issues/22#issuecomment-119265616

This handler does not expect data like some gateways, but a full HTML page that it then displays to the user from its own domain. That page can be the final "thank you" page with a link back to the merchant site, or can contain a HTML (meta, JS) redirect back to the site. If using DPM, then you *must* have a redirect if you want to catch form errors and give the user another chance to re-submit the payment form.

Anyway, there is a `$response->redirect()` helper method in the `completeResponse` to do a simple redirect for you, or you can provide your own HTML page from your application. It could do a `$response->redirect()` automatically, as described above, but if you want to provide your own HTML page, then that has to be something that can be switched off (or mess around with output buffers to catch the default redirect page and throw it away - I guess that might be okay for people who want something special, and the built-in redirect as the default).

**Comment by judgej** [comment] 2016-09-06 17:43
Fixed in PR #69 - use the `acceptNotification` handler, pointed to by the `notifyUrl` when creating the initial transaction.

**Closed by judgej** 2016-09-06 17:43 UTC
Labels: enhancement, V3

**Comment by coatesap** [comment] 2016-12-14 17:36
Hi @judgej, sorry to return to this after so long. I noticed in PR #69 that you've marked `completePurchase()` as deprecated. Is this meant just for the SagePay driver, or are you saying that it should be deprecated across all drivers/gateways?

**Comment by judgej** [comment] 2016-12-14 17:59
Hi @coatesap - it was just for this driver. It will remain for OmniPay 2.x but won't be needed in 3.x. I'll explain.

The very early OmniPay drivers used a `completePurchase()` to process parameters POSTed (or GET parameters) with a user return from an external gateway. So the user goes off to the external gateway, and they come back with some data that indicates the result of the transaction. It would normally be encrypted or hashed to make sure it does not get manipulated by the user, and the `completePurchase()` function would do the decrypting or check that hash.

Later there came gateway drivers with a back-channel. The results went direct from gateway to merchant site. To capture those results, the `completePurchase()` function was utilised because it seemed like the best fit. This is what the Sage Pay Server driver does. However, it was not an ideal fit, since `completePurchase()` was designed with a browser request in mind.

So later OmniPay introduced `acceptNotification()` which is solely for back-end server-to-server notification requests. I introduced that function to Sage Pay Server to use instead of `completePurchase()` for the Sage Pay Server driver. It also fixes a few flaws in the original `completePurchase()` (e.g. it could not response to an error condition if the hash failed because it threw an exception instead of returning the message to response with). I didn't want to change that functionality of `completePurchase()` as it would be a BC break. So the idea was to move to the `acceptNotification()` and let `completePurchase()` fade away.

Now `completePurchase()` still has its place where designed. For example, it can be used to catch 3D Secure codes POSTed back to the merchant site with the end user on return from the remote bank (or in same cases, on return from the payment gateway that *wraps* 3D Secure its own iframe-based page - e.g. PAYONE).

So personally I think it should be deprecated across all drivers where it is used as a back-channel POST/GET parser, but it does still have its place where used as a front-end POST/GET parser. However, there is no official policy on changing this across the board on any kind of time frame.

Does that make sense?

**Comment by judgej** [comment] 2016-12-14 18:07
Just a note on the difference between the back-end and front end handlers: on the back end, the notification handler normally has full control of the server request - it parses what comes in and returns the result. It is the kind of thing that would go into HTTP middleware, and would return its own HTTP response message. It could go into a controller, but not on a path any user would interact with.

The front-end handler on the other hand still accepts the incoming HTTP request, but does not control the response in any way. It just provides some data for whatever calls it. It may also be put into middleware, but it is probably better suited to going into a controller where the controller decides what to do and where to send the user to next.

**Comment by coatesap** [comment] 2016-12-15 07:53
Thanks @judgej, that's useful, and makes perfect sense based on what we previously discussed. My only concern is that aside from us, other driver developers may not be aware of what the intention is (or even the existence) of `acceptNotification()`. Would it be possible to add a condensed version of your previous comment to the docs, and mention it as an optional method in the [interface](https://github.com/thephpleague/omnipay-common/blob/master/src/Omnipay/Common/GatewayInterface.php)?

The application that I work on relies on being able to easily switch between different payment drivers, and so I'm very keen to see as much consistency between them as possible!

**Comment by judgej** [comment] 2016-12-20 00:29
Okay, on my list for when I get half an hour idle after Christmas.

**Comment by judgej** [comment] 2017-01-10 13:32
@coatesap Does this note cover this enough:

https://github.com/thephpleague/omnipay/pull/417

The overall descriptions of the difference between the `complete*` messages and the `acceptNotification` handler, I think, is great already. This note just acknowledges that that there is some cross-over still for historical reasons, but that is being addressed.
